## Get Single User
GET http://localhost:5000/api/users?correo=a@a.com&password=a

### Get User by ID
GET https://dasw-application.herokuapp.com/api/users?id=100

### Post nuevo usuario
POST https://dasw-application.herokuapp.com/api/users
Content-Type: application/json

{
      "id": 100,
      "nombre": "Óscar",
      "apellido": "González",
      "correo": "ogonzalez@iteso.mx",
      "password": "123456",
      "listaMaterias": [],
      "listaExamenes": [],
      "listaTareas": []
    }

### Actualizar usuario
PUT https://dasw-application.herokuapp.com/api/users/2
Content-Type: application/json

{
      "nombre": "Ricardo",
      "apellido": "Díaz",
      "correo": "rdiaz@iteso.mx",
      "password": "helloWorld",
      "listaMaterias": [],
      "listaExamenes": [],
      "listaTareas": []
    }

### Eliminar usuario
DELETE https://dasw-application.herokuapp.com/api/users/4

### Cargar Token
PUT https://dasw-application.herokuapp.com/api/token
Content-Type: application/json

{
  "userId": 2,
  "token": "BBBB"
}

### Ir por token
GET https://dasw-application.herokuapp.com/api/token


### POST token
POST https://dasw-application.herokuapp.com/api/token