## Get Single User
GET http://localhost:5000/api/users?correo=a@a.com&password=a

### Get User by ID
GET http://localhost:5000/api/users?id=4

### Post nuevo usuario
POST http://localhost:5000/api/users
Content-Type: application/json

{
      "id": 3,
      "nombre": "BBB",
      "apellido": "b",
      "correo": "b@b.com",
      "password": "b",
      "listaMaterias": [],
      "listaExamenes": [],
      "listaTareas": []
    }

### Actualizar usuario
PUT http://localhost:5000/api/users/3
Content-Type: application/json

{
      "nombre": "se",
      "apellido": "dgas",
      "correo": "d@d.com",
      "password": "d",
      "listaMaterias": [],
      "listaExamenes": [],
      "listaTareas": []
    }

### Eliminar usuario
DELETE http://localhost:5000/api/users/9

### Cargar Token
PUT http://localhost:5000/api/token
Content-Type: application/json

{
  "userId": 1,
  "token": "AAAA"
}

### Ir por token
GET http://localhost:5000/api/token